export const FETCH_POKEMON_LIST_REQUESTED = 'pokemon/FETCH_POKEMON_LIST_REQUESTED';
export const FETCH_POKEMON_LIST_SUCCEEDED = 'pokemon/FETCH_POKEMON_LIST_SUCCEEDED';
export const FETCH_POKEMON_LIST_FAILED = 'pokemon/FETCH_POKEMON_LIST_FAILED';

export const FETCH_EVOLUTION_CHAIN_REQUESTED = 'pokemon/FETCH_EVOLUTION_CHAIN_REQUESTED';
export const FETCH_EVOLUTION_CHAIN_SUCCEEDED = 'pokemon/FETCH_EVOLUTION_CHAIN_SUCCEEDED';
export const FETCH_EVOLUTION_CHAIN_FAILED = 'pokemon/FETCH_EVOLUTION_CHAIN_FAILED';

export const SET_POKEMON_SPECIES_DATA = 'pokemon/SET_POKEMON_SPECIES_DATA';
export const SET_POKEMON_LOCATION_DATA = 'pokemon/SET_POKEMON_LOCATION_DATA';
